############################################################################################################################################################################
library(ggplot2);library(dplyr); library(DataCombine)
library(glmnet); library(nhlscrapr); library(caret); library(RMySQL); library(readr); library(reshape2); library(rvest)
library(httr); library(data.table); library("reshape2");
library(shiny)
library(ggplot2)
library(xts)
library(RMySQL)
library(DBI)
theme_set(theme_bw())


txt <- element_text(size = 12, colour = "grey25", face = "plain")
bold_txt <- element_text(size = 20, colour = "navy", face = "bold")

theme_standard <- function(base_size = 16, base_family = "") {
  theme_bw(base_size = base_size, base_family = base_family) +
    theme(
      strip.background = element_blank(), 
      
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      #panel.grid.major.y = element_line( colour = "white", size = 2), 
      panel.grid.major.x = element_line( colour = "white", size = 2), 
      
      panel.background = element_rect(fill="grey90"),
      plot.background = element_rect(fill="grey90"),
      legend.background = element_rect(fill="grey90"),
      legend.key = element_rect(fill="grey90", size = 20),
      legend.key.size = unit(1,"cm"),
      
      panel.border = element_blank(), 
      
      line = element_line( colour = "white", size = 2),
      axis.text.x = element_text(angle = 90, hjust = 1),
      text = txt, 
      plot.title = bold_txt, 
      
      axis.title = txt, 
      axis.text = txt, 
      
      legend.title = bold_txt, 
      legend.text = txt ) 
}
############################################################################################################################################################################
########1.A DATA PREP
############################################################################################################################################################################

# Load Scored Data
scored_data <- read.csv("~/Documents/CWA/HockeyScrape/scored_data_2018.csv") %>%
  mutate(xG = xG_raw,
         xG_team = ifelse(is_Rebound == 0, xG_raw,
                          ifelse(is_Rebound == 1 & lag(is_Rebound) == 0, xG_raw * (1-lag(xG_raw)),
                                 ifelse(is_Rebound == 1 & lag(is_Rebound) == 1 & lag(is_Rebound,2) == 0,
                                        xG_raw * (1-lag(xG_raw)) * (1-lag(xG_raw,2)),
                                        ifelse(is_Rebound == 1 & lag(is_Rebound) == 1 & lag(is_Rebound,2) == 1 & lag(is_Rebound,3) == 0,
                                               xG_raw * (1-lag(xG_raw)) * (1-lag(xG_raw,2)) * (1-lag(xG_raw,3)),
                                               ifelse(is_Rebound == 1 & lag(is_Rebound) == 1 & lag(is_Rebound,2) == 1 & lag(is_Rebound,3) == 1 & lag(is_Rebound,4) == 0,
                                                      xG_raw * (1-lag(xG_raw)) * (1-lag(xG_raw,2)) * (1-lag(xG_raw,3)) * (1-lag(xG_raw,4)),
                                                      xG_raw * (1-lag(xG_raw)) * (1-lag(xG_raw,2)) * (1-lag(xG_raw,3)) * (1-lag(xG_raw,4))))))))



### 1. Scored Data from 2009-2017 and ready for analysis

```{r}

## Beta Functions
calcBetaMode <- function(aa, bb) { BetaMode <- (aa - 1)/(aa + bb - 2); return(BetaMode); }
calcBetaMean <- function(aa, bb) { BetaMean <- (aa)/(aa + bb); return(BetaMean); }
calcBetaSd   <- function(aa, bb) { BetaSd <- sqrt((aa * bb)/(((aa + bb)^2) * (aa + bb + 1))); return(BetaSd); }

conn <- dbConnect(MySQL(), user='ca_elo_games', password='cprice31!',
                  host='mysql.crowdscoutsports.com', db='nhl_all')
on.exit(dbDisconnect(conn))

goalie_roster <- dbGetQuery(conn, "SELECT distinct upper(playerName) as `SA_Goalie`, playerId as nhl_id, playerHeight as height,  
                            playerShootsCatches as Catches, playerBirthDate as dob FROM `nhl_all`.`hockey_goalies_roster` AS A")


goalie_roster <- goalie_roster %>%
  mutate(SA_Goalie = ifelse(SA_Goalie == "MATTHEW MURRAY","MATT MURRAY",
                            ifelse(SA_Goalie == "OLIE KOLZIG","OLAF KOLZIG",
                                   ifelse(SA_Goalie == "STEPHEN VALIQUETTE","STEVE VALIQUETTE",
                                          ifelse(SA_Goalie == "THOMAS MCCOLLUM","TOM MCCOLLUM",
                                                 ifelse(SA_Goalie == "JEAN-SEBASTIEN AUBIN", "J-SEBASTIEN AUBIN",
                                                        ifelse(SA_Goalie == "ALEXANDER PECHURSKIY","ALEXANDER PECHURSKI",
                                                               SA_Goalie))))))) %>%
  unique()


load("~/Documents/CWA/Hockey Data/xG.scored.data.RData")

goalie_data_prep <- scored_data %>%
  filter(season != "20072008") %>%
  mutate(SA_Goalie = ifelse(SA_Goalie == "STEPHEN VALIQUETTE","STEVE VALIQUETTE",
                            ifelse(SA.Goalie == "THOMAS MCCOLLUM","TOM MCCOLLUM",
                                   ifelse(SA_Goalie == "MATTHEW MURRAY","MATT MURRAY",
                                          SA_Goalie))),

         NonRebound_Shot = ifelse(is_Rebound == 0, 1, 0),
         xG_FirstShot = ifelse(is_Rebound == 0, xG, 0)) 

rebound_goal_probability <- goalie_data_prep %>% 
  filter(is.Rebound == 1) %>%
  summarise(rebound_goal_probability = sum(as.numeric(goal)-1) / n())

goalie_shot_level_prep <- goalie_data_prep %>%
  cbind(rebound_goal_probability) %>%
  left_join(goalie_roster, by ="SA_Goalie") %>%
  mutate(Age = round((as.Date(paste0("10/1/",as.numeric(substr(season,1,4))), format = "%m/%d/%Y") - as.Date(dob)) / 365.25,1)) 


